# Generated by Django 4.2.2 on 2023-06-15 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='date',
            new_name='company',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
