# Generated by Django 4.2.2 on 2023-06-15 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_date_joblisting_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
