# Generated by Django 4.2.2 on 2023-06-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_joblisting_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
