# Generated by Django 4.2.2 on 2023-06-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_joblisting_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='hash',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
