# Generated by Django 3.2.2 on 2023-06-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_companyjobcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyJobCount',
        ),
    ]
