# Generated by Django 3.2.2 on 2023-06-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='career_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jobs.Tag'),
        ),
    ]
