# Generated by Django 3.2.2 on 2023-06-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20230620_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='description',
        ),
    ]
