# Generated by Django 3.2.2 on 2023-06-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_joblisting_description'),
    ]

    operations = [
    ]
