# Generated by Django 3.2.2 on 2023-06-22 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20230621_1655'),
    ]

    operations = [
    ]
