# Generated by Django 3.2.2 on 2023-06-22 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20230621_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='discovered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
