# Generated by Django 3.2.2 on 2023-06-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_joblisting_discovered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='discovered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
