# Generated by Django 3.2.2 on 2023-06-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_joblisting_discovered_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joblisting',
            unique_together={('title', 'link')},
        ),
    ]
