# Generated by Django 3.2.2 on 2023-06-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_joblisting_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joblisting',
            unique_together=set(),
        ),
    ]
