# Generated by Django 3.2.2 on 2023-06-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alter_joblisting_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_base_url',
            field=models.URLField(null=True),
        ),
    ]
