# Generated by Django 3.2.2 on 2023-07-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='state_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
