# Generated by Django 3.2.2 on 2023-07-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_joblisting_state_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='state_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
