# Generated by Django 3.2.2 on 2023-07-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_auto_20230707_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth0_user_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
