# Generated by Django 3.2.2 on 2023-07-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_userprofile_auth0_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_companies',
            field=models.ManyToManyField(blank=True, to='jobs.Company'),
        ),
    ]
