job_titles = [
    "Account Executive",
    "Account Manager",
    "Accountant",
    "Accounting Clerk",
    "Actuary",
    "Administrative Assistant",
    "Advertising Manager",
    "Analyst",
    "Android Developer",
    "Architect",
    "Art Director",
    "Assembler",
    "Assistant Manager",
    "Attorney",
    "Auditor",
    "Auto Mechanic",
    "Baker",
    "Bank Teller",
    "Barista",
    "Bartender",
    "Beauty Therapist",
    "Biologist",
    "Bookkeeper",
    "Branch Manager",
    "Brand Manager",
    "Business Analyst",
    "Business Consultant",
    "Business Development Manager",
    "Butcher",
    "Buyer",
    "CEO",
    "CFO",
    "CIO",
    "CTO",
    "Chef",
    "Chemist",
    "Chief Engineer",
    "Civil Engineer",
    "Claims Adjuster",
    "Clinical Research Associate",
    "Co-Founder",
    "Commercial Manager",
    "Communications Director",
    "Communications Manager",
    "Community Manager",
    "Compliance Officer",
    "Construction Manager",
    "Construction Worker",
    "Consultant",
    "Content Manager",
    "Content Writer",
    "Controller",
    "Copywriter",
    "Creative Director",
    "Credit Analyst",
    "Customer Service Representative",
    "Data Analyst",
    "Data Engineer",
    "Data Scientist",
    "Database Administrator",
    "Delivery Driver",
    "Dentist",
    "Design Engineer",
    "Designer",
    "Desktop Support",
    "Developer",
    "Development Director",
    "Digital Marketing Manager",
    "Doctor",
    "Driver",
    "Editor",
    "Editorial Assistant",
    "Electrical Engineer",
    "Electrician",
    "Engineer",
    "Event Coordinator",
    "Event Manager",
    "Executive Assistant",
    "Executive Director",
    "Facility Manager",
    "Finance Director",
    "Finance Manager",
    "Financial Analyst",
    "Financial Controller",
    "Financial Planner",
    "Firefighter",
    "Flight Attendant",
    "Food Technologist",
    "Front End Developer",
    "Front Office Manager",
    "Graphic Designer",
    "Guidance Counselor",
    "HR Coordinator",
    "HR Manager",
    "Hairdresser",
    "Head Chef",
    "Health and Safety Officer",
    "Healthcare Assistant",
    "Healthcare Worker",
    "Help Desk",
    "Hotel Manager",
    "Housekeeper",
    "HR Specialist",
    "IT Analyst",
    "IT Consultant",
    "IT Director",
    "IT Manager",
    "IT Support",
    "IT Technician",
    "Illustrator",
    "Industrial Engineer",
    "Industrial Designer",
    "Insurance Agent",
    "Interior Designer",
    "Journalist",
    "Key Account Manager",
    "Kindergarten Teacher",
    "Lab Technician",
    "Landscape Architect",
    "Lawyer",
    "Legal Advisor",
    "Legal Secretary",
    "Librarian",
    "Logistics Coordinator",
    "Logistics Manager",
    "Maintenance Engineer",
    "Maintenance Manager",
    "Maintenance Technician",
    "Management Consultant",
    "Manager",
    "Manufacturing Engineer",
    "Market Research Analyst",
    "Marketing Assistant",
    "Marketing Coordinator",
    "Marketing Director",
    "Marketing Executive",
    "Marketing Manager",
    "Massage Therapist",
    "Mechanic",
    "Mechanical Engineer",
    "Media Planner",
    "Medical Assistant",
    "Medical Receptionist",
    "Medical Secretary",
    "Merchandiser",
    "Network Engineer",
    "Nurse",
    "Nurse Practitioner",
    "Office Administrator",
    "Office Assistant",
    "Office Clerk",
    "Office Manager",
    "Operations Manager",
    "Optician",
    "Optometrist",
    "PA",
    "Paralegal",
    "Paramedic",
    "Patent Attorney",
    "Payroll Administrator",
    "Pharmacist",
    "Pharmacy Technician",
    "Photographer",
    "Physician",
    "Physiotherapist",
    "Pilot",
    "Plumber",
    "Police Officer",
    "Portfolio Manager",
    "Product Manager",
    "Product Owner",
    "Production Manager",
    "Production Worker",
    "Program Manager",
    "Programmer",
    "Project Coordinator",
    "Project Engineer",
    "Project Manager",
    "Property Manager",
    "Psychologist",
    "QA Tester",
    "Quality Assurance Engineer",
    "Quality Manager",
    "Quantity Surveyor",
    "Radiographer",
    "Real Estate Agent",
    "Receptionist",
    "Recruiter",
    "Recruitment Consultant",
    "Registered Nurse",
    "Relationship Manager",
    "Reporter",
    "Research Analyst",
    "Research Assistant",
    "Researcher",
    "Restaurant Manager",
    "Retail Assistant",
    "Retail Manager",
    "Risk Manager",
    "Sales Assistant",
    "Sales Associate",
    "Sales Coordinator",
    "Sales Director",
    "Sales Engineer",
    "Sales Executive",
    "Sales Manager",
    "Sales Representative",
    "School Counselor",
    "Secretary",
    "Security Guard",
    "Security Officer",
    "SEO Specialist",
    "Service Manager",
    "Social Media Manager",
    "Social Worker",
    "Software Developer",
    "Software Engineer",
    "Solution Architect",
    "Solicitor",
    "Store Manager",
    "Strategy Manager",
    "Supply Chain Manager",
    "Systems Administrator",
    "Systems Engineer",
    "Tax Consultant",
    "Teacher",
    "Technical Director",
    "Technical Manager",
    "Technical Support",
    "Technical Writer",
    "Technician",
    "Telemarketer",
    "Telesales",
    "Test Engineer",
    "Trainer",
    "Training Manager",
    "Translator",
    "Travel Agent",
    "UI Designer",
    "UX Designer",
    "Vet",
    "Warehouse Manager",
    "Warehouse Worker",
    "Web Designer",
    "Web Developer",
    "Welder",
    "Writer",
    "iOS Developer",
    "Sales Consultant",
    "Customer Service Manager",
    "Product Designer",
    "Financial Advisor",
    "Account Coordinator",
    "Project Assistant",
    "Sales Support",
    "Marketing Consultant",
    "Marketing Specialist",
    "IT Project Manager",
    "HR Administrator",
    "Network Administrator",
    "Security Engineer",
    "Data Manager",
    "Brand Ambassador",
    "Web Master",
    "UX Researcher",
    "QA Analyst",
    "Community Outreach",
    "DevOps Engineer",
    "Graphic Artist",
    "HR Assistant",
    "Medical Officer",
    "Marketing Analyst",
    "Business Development Coordinator",
    "Sales Officer",
    "Clinical Pharmacist",
    "Clinical Nurse",
    "IT Analyst",
    "QA Specialist",
    "Product Development Manager",
    "Public Relations Officer",
    "Digital Marketing Specialist",
    "Clinical Research Coordinator",
    "Product Marketing Manager",
    "Research Scientist",
    "Sales Analyst",
    "Business Systems Analyst",
    "Chartered Accountant",
    "Data Analyst Intern",
    "Database Developer",
    "Dental Assistant",
    "Design Manager",
    "Development Assistant",
    "Editorial Director",
    "Financial Reporting Manager",
    "Fleet Manager",
    "IT Operations Manager",
    "Java Developer",
    "Legal Counsel",
    "Media Director",
    "Network Security Engineer",
    "Nurse Coordinator",
    "Nutritionist",
    "Office Coordinator",
    "Operations Analyst",
    "Organizational Development Manager",
    "Payroll Specialist",
    "Program Analyst",
    "Public Relations Assistant",
    "Quality Assurance Manager",
    "Real Estate Development Manager",
    "Recruitment Manager",
    "Regulatory Affairs Specialist",
    "Research Engineer",
    "Residential Counselor",
    "Resource Manager",
    "Retail Store Manager",
    "Sales and Marketing Manager",
    "Senior Consultant",
    "Service Coordinator",
    "Staff Accountant",
    "Strategy Analyst",
    "Technical Project Manager",
    "Test Manager",
    "Treasurer",
    "Web Developer Intern",
    "Workforce Development Specialist"
]
